version: 2.1
setup: true
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/orb-tools
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
          exclude: RC009 # 64 is too short as the commands line lenth limit
      - shellcheck/check:
          filters: *filters
      - orb-tools/publish:
          orb-name: solidusio/extensions
          vcs-type: << pipeline.project.type >>
          enable-pr-comment: false
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters
