version: 2.1
orbs:
  extensions: solidusio/extensions@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  test-run-with-postgres:
    executor: extensions/postgres
    steps:
      - checkout
      - extensions/run-tests-solidus-older:
          working_directory: '~/project/solidus_dummy_extension'
      - extensions/store-test-results
  test-run-with-mysql:
    executor: extensions/mysql
    steps:
      - checkout
      - extensions/run-tests-solidus-current:
          working_directory: '~/project/solidus_dummy_extension'
      - extensions/store-test-results
  test-run-with-sqlite:
    executor: extensions/sqlite
    steps:
      - checkout
      - extensions/run-tests-solidus-master:
          working_directory: '~/project/solidus_dummy_extension'
      - extensions/store-test-results
  test-run-linting-code:
    executor: extensions/sqlite-memory
    steps:
      - extensions/lint-code:
          working_directory: '~/project/solidus_dummy_extension'


workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - test-run-with-postgres:
          filters: *filters
      - test-run-with-mysql:
          filters: *filters
      - test-run-with-sqlite:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: solidusio/extensions
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - test-run-with-postgres
            - test-run-with-mysql
            - test-run-with-sqlite
          enable-pr-comment: false
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
