version: 2.1
orbs:
  extensions: solidusio/extensions@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    executor: extensions/sqlite-memory
    steps:
      - checkout
      - run:
          name: Dummy extension project
          command: |
            bundle init
            bundle add rake
            echo "task(:default) { puts ENV['SOLIDUS_BRANCH'] }" > Rakefile
            bundle install
      - extensions/run-tests

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: solidusio/extensions
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          enable-pr-comment: false
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
